-- MySQL Script generated by MySQL Workbench
-- Sat Nov 19 20:22:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aero
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aero
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aero` DEFAULT CHARACTER SET utf8 ;
USE `aero` ;

-- -----------------------------------------------------
-- Table `aero`.`Passageiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aero`.`Passageiro` (
  `nome` VARCHAR(45) NOT NULL,
  `CPF` INT NOT NULL,
  `RG` INT NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `telefone` INT NOT NULL,
  `telefone_cel` INT NOT NULL,
  `genero` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `passaporte` VARCHAR(7) NOT NULL,
  `senha` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`RG`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aero`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aero`.`Pagamento` (
  `nome_cartao` VARCHAR(45) NOT NULL,
  `numero_cartao` INT NOT NULL,
  `validade` DATETIME NOT NULL,
  `Codigo` INT NOT NULL,
  `codigo_passagem` VARCHAR(45) NOT NULL,
  `Passageiro_RG` INT NOT NULL,
  PRIMARY KEY (`Passageiro_RG`, `codigo_passagem`),
  CONSTRAINT `fk_Pagamento_Passageiro`
    FOREIGN KEY (`Passageiro_RG`)
    REFERENCES `aero`.`Passageiro` (`RG`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
